// <auto-generated />
using System;
using GearNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearNet.Migrations
{
    [DbContext(typeof(GearNetContext))]
    [Migration("20240321000246_addAddress")]
    partial class addAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearNet.Entities.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Duration")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("GearNet.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("Address")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RackCol")
                        .HasColumnType("int");

                    b.Property<int?>("RackRow")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DeviceId");

                    b.HasIndex("CaseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GearNet.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GearNet.Entities.Case", b =>
                {
                    b.HasOne("GearNet.Entities.Student", "Student")
                        .WithMany("Cases")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GearNet.Entities.Device", b =>
                {
                    b.HasOne("GearNet.Entities.Case", "Case")
                        .WithMany("Devices")
                        .HasForeignKey("CaseId");

                    b.HasOne("GearNet.Entities.Student", "Student")
                        .WithMany("Devices")
                        .HasForeignKey("StudentId");

                    b.Navigation("Case");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GearNet.Entities.Case", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("GearNet.Entities.Student", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
